//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP1_Module1_Version1._1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fypEntities : DbContext
    {
        public fypEntities()
            : base("name=fypEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fyp_group> fyp_group { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<conversation> conversations { get; set; }
        public virtual DbSet<milestone> milestones { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<registration> registrations { get; set; }
        public virtual DbSet<iteration> iterations { get; set; }
        public virtual DbSet<idea> ideas { get; set; }
    }
}
