//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP1_Module1_Version1._1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class fyp_group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fyp_group()
        {
            this.conversations = new HashSet<conversation>();
            this.notifications = new HashSet<notification>();
            this.registrations = new HashSet<registration>();
        }
    
        public int group_id { get; set; }
        [Required]
        [Display(Name = "Group Member 1:")]
        public int group_member1 { get; set; }
        [Required]
        [Display(Name = "Group Member 2:")]
        public int group_member2 { get; set; }
        [Required]
        [Display(Name = "Group Member 3:")]
        public int group_member3 { get; set; }
        public List<student> students { get; set; }
        public virtual student student { get; set; }
        public virtual student student1 { get; set; }
        public virtual student student2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conversation> conversations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification> notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registration> registrations { get; set; }
    }
}
