//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP1_Module1_Version1._1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class idea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public idea()
        {
            this.conversations = new HashSet<conversation>();
            this.registrations = new HashSet<registration>();
            this.notifications = new HashSet<notification>();
        }
    
        public int Id { get; set; }
        [Required]
        [Display(Name = "Title:")]
        public string Title { get; set; }
        [Required]
        [Display(Name = "Description:")]
        public string Description { get; set; }
        [Required]
        [Display(Name = "Category:")]
        public string Category { get; set; }
        public Nullable<int> PostedByTeacher { get; set; }
        public Nullable<int> PostedByStudent { get; set; }
        public int checker { get; set; }
        public int approve { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conversation> conversations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registration> registrations { get; set; }
        public virtual student student { get; set; }
        public virtual teacher teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification> notifications { get; set; }
    }
}
