//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP1_Module1_Version1._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iteration
    {
        public int id { get; set; }
        public int milestoneId { get; set; }
        public int iterationId { get; set; }
    
        public virtual milestone milestone { get; set; }
    }
}
