//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP1_Module1_Version1._1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class milestone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public milestone()
        {
            this.iterations = new HashSet<iteration>();
        }
    
        public int idmileStones { get; set; }
        [Required]
        [Display(Name = "Name:")]
        public string name { get; set; }
        [Required]
        [Display(Name = "Complexity:")]
        public int complexity { get; set; }
        [Required]
        [Display(Name = "Description:")]
        public string description { get; set; }
        public int idregistration { get; set; }
    
        public virtual registration registration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iteration> iterations { get; set; }
    }
}
