//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP1_Module1_Version1._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int idnotification { get; set; }
        public int group { get; set; }
        public int idea { get; set; }
        public string notifier { get; set; }
        public int seen { get; set; }
        public string type { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<int> registration { get; set; }
    
        public virtual fyp_group fyp_group { get; set; }
        public virtual registration registration1 { get; set; }
        public virtual idea idea1 { get; set; }
    }
}
