//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP1_Module1_Version1._1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public registration()
        {
            this.milestones = new HashSet<milestone>();
            this.notifications = new HashSet<notification>();
        }
    
        public int idRegistration { get; set; }
        public int fypgroup { get; set; }
        public int supervisor { get; set; }
        public int idea { get; set; }
        [Required]
        [Display(Name = "Co Supervisor Name:")]
        public string co_supervisorName { get; set; }
        public string registrationcol { get; set; }
        public int approve { get; set; }
        [Required]
        [Display(Name = "Co Supervisor Email:")]
        [DataType(DataType.EmailAddress)]
        public string co_supervisorEmail { get; set; }
    
        public virtual fyp_group fyp_group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<milestone> milestones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification> notifications { get; set; }
        public virtual teacher teacher { get; set; }
        public virtual idea idea1 { get; set; }
    }
}
